apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: occurance-traker-prod
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: prod
    server: https://kubernetes.default.svc
  project: default
  sources:
    - repoURL: https://github.com/NHristovski/GHArgoAppOfApps.git
      path: occurance-traker-prod
      targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
