apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis-dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: dev
    server: https://kubernetes.default.svc
  project: default
  sources:
    - repoURL: registry-1.docker.io/bitnamicharts
      path: redis
      chart: redis
      targetRevision: 20.7.0
      helm:
        values: |
          global:
            redis:
              password: redis
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true