apiVersion: v1
kind: ConfigMap
metadata:
  name: occurrance-traker
data:
  application.yaml: |
    spring:
      application:
        name: OccurenceTrakerApplication
      data:
        redis:
          host: redis-prod-master.prod.svc.cluster.local
          port: 6379
          usePassword: true
          password: redis

